// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagelogpayload"
)

// UsageLogPayloadCreate is the builder for creating a UsageLogPayload entity.
type UsageLogPayloadCreate struct {
	config
	mutation *UsageLogPayloadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *UsageLogPayloadCreate) SetUsageLogID(v int64) *UsageLogPayloadCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *UsageLogPayloadCreate) SetRequestBody(v string) *UsageLogPayloadCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *UsageLogPayloadCreate) SetNillableRequestBody(v *string) *UsageLogPayloadCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *UsageLogPayloadCreate) SetResponseBody(v string) *UsageLogPayloadCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *UsageLogPayloadCreate) SetNillableResponseBody(v *string) *UsageLogPayloadCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetRequestTruncated sets the "request_truncated" field.
func (_c *UsageLogPayloadCreate) SetRequestTruncated(v bool) *UsageLogPayloadCreate {
	_c.mutation.SetRequestTruncated(v)
	return _c
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_c *UsageLogPayloadCreate) SetNillableRequestTruncated(v *bool) *UsageLogPayloadCreate {
	if v != nil {
		_c.SetRequestTruncated(*v)
	}
	return _c
}

// SetResponseTruncated sets the "response_truncated" field.
func (_c *UsageLogPayloadCreate) SetResponseTruncated(v bool) *UsageLogPayloadCreate {
	_c.mutation.SetResponseTruncated(v)
	return _c
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_c *UsageLogPayloadCreate) SetNillableResponseTruncated(v *bool) *UsageLogPayloadCreate {
	if v != nil {
		_c.SetResponseTruncated(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogPayloadCreate) SetCreatedAt(v time.Time) *UsageLogPayloadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogPayloadCreate) SetNillableCreatedAt(v *time.Time) *UsageLogPayloadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the UsageLogPayloadMutation object of the builder.
func (_c *UsageLogPayloadCreate) Mutation() *UsageLogPayloadMutation {
	return _c.mutation
}

// Save creates the UsageLogPayload in the database.
func (_c *UsageLogPayloadCreate) Save(ctx context.Context) (*UsageLogPayload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogPayloadCreate) SaveX(ctx context.Context) *UsageLogPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogPayloadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogPayloadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogPayloadCreate) defaults() {
	if _, ok := _c.mutation.RequestTruncated(); !ok {
		v := usagelogpayload.DefaultRequestTruncated
		_c.mutation.SetRequestTruncated(v)
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		v := usagelogpayload.DefaultResponseTruncated
		_c.mutation.SetResponseTruncated(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelogpayload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogPayloadCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "UsageLogPayload.usage_log_id"`)}
	}
	if _, ok := _c.mutation.RequestTruncated(); !ok {
		return &ValidationError{Name: "request_truncated", err: errors.New(`ent: missing required field "UsageLogPayload.request_truncated"`)}
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		return &ValidationError{Name: "response_truncated", err: errors.New(`ent: missing required field "UsageLogPayload.response_truncated"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLogPayload.created_at"`)}
	}
	return nil
}

func (_c *UsageLogPayloadCreate) sqlSave(ctx context.Context) (*UsageLogPayload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogPayloadCreate) createSpec() (*UsageLogPayload, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLogPayload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelogpayload.Table, sqlgraph.NewFieldSpec(usagelogpayload.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(usagelogpayload.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(usagelogpayload.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = &value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogpayload.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = &value
	}
	if value, ok := _c.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldRequestTruncated, field.TypeBool, value)
		_node.RequestTruncated = value
	}
	if value, ok := _c.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldResponseTruncated, field.TypeBool, value)
		_node.ResponseTruncated = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelogpayload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogPayload.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogPayloadUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogPayloadCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogPayloadUpsertOne {
	_c.conflict = opts
	return &UsageLogPayloadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogPayloadCreate) OnConflictColumns(columns ...string) *UsageLogPayloadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogPayloadUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogPayloadUpsertOne is the builder for "upsert"-ing
	//  one UsageLogPayload node.
	UsageLogPayloadUpsertOne struct {
		create *UsageLogPayloadCreate
	}

	// UsageLogPayloadUpsert is the "OnConflict" setter.
	UsageLogPayloadUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogPayloadUpsert) SetUsageLogID(v int64) *UsageLogPayloadUpsert {
	u.Set(usagelogpayload.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogPayloadUpsert) UpdateUsageLogID() *UsageLogPayloadUpsert {
	u.SetExcluded(usagelogpayload.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageLogPayloadUpsert) AddUsageLogID(v int64) *UsageLogPayloadUpsert {
	u.Add(usagelogpayload.FieldUsageLogID, v)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogPayloadUpsert) SetRequestBody(v string) *UsageLogPayloadUpsert {
	u.Set(usagelogpayload.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsert) UpdateRequestBody() *UsageLogPayloadUpsert {
	u.SetExcluded(usagelogpayload.FieldRequestBody)
	return u
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *UsageLogPayloadUpsert) ClearRequestBody() *UsageLogPayloadUpsert {
	u.SetNull(usagelogpayload.FieldRequestBody)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogPayloadUpsert) SetResponseBody(v string) *UsageLogPayloadUpsert {
	u.Set(usagelogpayload.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsert) UpdateResponseBody() *UsageLogPayloadUpsert {
	u.SetExcluded(usagelogpayload.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *UsageLogPayloadUpsert) ClearResponseBody() *UsageLogPayloadUpsert {
	u.SetNull(usagelogpayload.FieldResponseBody)
	return u
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogPayloadUpsert) SetRequestTruncated(v bool) *UsageLogPayloadUpsert {
	u.Set(usagelogpayload.FieldRequestTruncated, v)
	return u
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsert) UpdateRequestTruncated() *UsageLogPayloadUpsert {
	u.SetExcluded(usagelogpayload.FieldRequestTruncated)
	return u
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogPayloadUpsert) SetResponseTruncated(v bool) *UsageLogPayloadUpsert {
	u.Set(usagelogpayload.FieldResponseTruncated, v)
	return u
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsert) UpdateResponseTruncated() *UsageLogPayloadUpsert {
	u.SetExcluded(usagelogpayload.FieldResponseTruncated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogPayloadUpsertOne) UpdateNewValues() *UsageLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagelogpayload.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogPayloadUpsertOne) Ignore() *UsageLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogPayloadUpsertOne) DoNothing() *UsageLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogPayloadCreate.OnConflict
// documentation for more info.
func (u *UsageLogPayloadUpsertOne) Update(set func(*UsageLogPayloadUpsert)) *UsageLogPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogPayloadUpsertOne) SetUsageLogID(v int64) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageLogPayloadUpsertOne) AddUsageLogID(v int64) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertOne) UpdateUsageLogID() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogPayloadUpsertOne) SetRequestBody(v string) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertOne) UpdateRequestBody() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *UsageLogPayloadUpsertOne) ClearRequestBody() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.ClearRequestBody()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogPayloadUpsertOne) SetResponseBody(v string) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertOne) UpdateResponseBody() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *UsageLogPayloadUpsertOne) ClearResponseBody() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.ClearResponseBody()
	})
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogPayloadUpsertOne) SetRequestTruncated(v bool) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetRequestTruncated(v)
	})
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertOne) UpdateRequestTruncated() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateRequestTruncated()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogPayloadUpsertOne) SetResponseTruncated(v bool) *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertOne) UpdateResponseTruncated() *UsageLogPayloadUpsertOne {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateResponseTruncated()
	})
}

// Exec executes the query.
func (u *UsageLogPayloadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogPayloadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogPayloadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogPayloadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogPayloadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogPayloadCreateBulk is the builder for creating many UsageLogPayload entities in bulk.
type UsageLogPayloadCreateBulk struct {
	config
	err      error
	builders []*UsageLogPayloadCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLogPayload entities in the database.
func (_c *UsageLogPayloadCreateBulk) Save(ctx context.Context) ([]*UsageLogPayload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLogPayload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogPayloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogPayloadCreateBulk) SaveX(ctx context.Context) []*UsageLogPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogPayloadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogPayloadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogPayload.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogPayloadUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogPayloadCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogPayloadUpsertBulk {
	_c.conflict = opts
	return &UsageLogPayloadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogPayloadCreateBulk) OnConflictColumns(columns ...string) *UsageLogPayloadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogPayloadUpsertBulk{
		create: _c,
	}
}

// UsageLogPayloadUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLogPayload nodes.
type UsageLogPayloadUpsertBulk struct {
	create *UsageLogPayloadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogPayloadUpsertBulk) UpdateNewValues() *UsageLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagelogpayload.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogPayload.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogPayloadUpsertBulk) Ignore() *UsageLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogPayloadUpsertBulk) DoNothing() *UsageLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogPayloadCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogPayloadUpsertBulk) Update(set func(*UsageLogPayloadUpsert)) *UsageLogPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogPayloadUpsertBulk) SetUsageLogID(v int64) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *UsageLogPayloadUpsertBulk) AddUsageLogID(v int64) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertBulk) UpdateUsageLogID() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogPayloadUpsertBulk) SetRequestBody(v string) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertBulk) UpdateRequestBody() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *UsageLogPayloadUpsertBulk) ClearRequestBody() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.ClearRequestBody()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogPayloadUpsertBulk) SetResponseBody(v string) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertBulk) UpdateResponseBody() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *UsageLogPayloadUpsertBulk) ClearResponseBody() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.ClearResponseBody()
	})
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogPayloadUpsertBulk) SetRequestTruncated(v bool) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetRequestTruncated(v)
	})
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertBulk) UpdateRequestTruncated() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateRequestTruncated()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogPayloadUpsertBulk) SetResponseTruncated(v bool) *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogPayloadUpsertBulk) UpdateResponseTruncated() *UsageLogPayloadUpsertBulk {
	return u.Update(func(s *UsageLogPayloadUpsert) {
		s.UpdateResponseTruncated()
	})
}

// Exec executes the query.
func (u *UsageLogPayloadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogPayloadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogPayloadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogPayloadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
