// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagelogpayload"
)

// UsageLogPayload is the model entity for the UsageLogPayload schema.
type UsageLogPayload struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 关联 usage_logs.id
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// 截断后的请求报文
	RequestBody *string `json:"request_body,omitempty"`
	// 截断后的响应报文
	ResponseBody *string `json:"response_body,omitempty"`
	// 请求报文是否被截断
	RequestTruncated bool `json:"request_truncated,omitempty"`
	// 响应报文是否被截断
	ResponseTruncated bool `json:"response_truncated,omitempty"`
	// 创建时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLogPayload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelogpayload.FieldRequestTruncated, usagelogpayload.FieldResponseTruncated:
			values[i] = new(sql.NullBool)
		case usagelogpayload.FieldID, usagelogpayload.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case usagelogpayload.FieldRequestBody, usagelogpayload.FieldResponseBody:
			values[i] = new(sql.NullString)
		case usagelogpayload.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLogPayload fields.
func (_m *UsageLogPayload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelogpayload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagelogpayload.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usagelogpayload.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = new(string)
				*_m.RequestBody = value.String
			}
		case usagelogpayload.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = new(string)
				*_m.ResponseBody = value.String
			}
		case usagelogpayload.FieldRequestTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_truncated", values[i])
			} else if value.Valid {
				_m.RequestTruncated = value.Bool
			}
		case usagelogpayload.FieldResponseTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_truncated", values[i])
			} else if value.Valid {
				_m.ResponseTruncated = value.Bool
			}
		case usagelogpayload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLogPayload.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLogPayload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageLogPayload.
// Note that you need to call UsageLogPayload.Unwrap() before calling this method if this UsageLogPayload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLogPayload) Update() *UsageLogPayloadUpdateOne {
	return NewUsageLogPayloadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLogPayload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLogPayload) Unwrap() *UsageLogPayload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLogPayload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLogPayload) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLogPayload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	if v := _m.RequestBody; v != nil {
		builder.WriteString("request_body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponseBody; v != nil {
		builder.WriteString("response_body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("request_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestTruncated))
	builder.WriteString(", ")
	builder.WriteString("response_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseTruncated))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogPayloads is a parsable slice of UsageLogPayload.
type UsageLogPayloads []*UsageLogPayload
