// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelogpayload"
)

// UsageLogPayloadUpdate is the builder for updating UsageLogPayload entities.
type UsageLogPayloadUpdate struct {
	config
	hooks    []Hook
	mutation *UsageLogPayloadMutation
}

// Where appends a list predicates to the UsageLogPayloadUpdate builder.
func (_u *UsageLogPayloadUpdate) Where(ps ...predicate.UsageLogPayload) *UsageLogPayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogPayloadUpdate) SetUsageLogID(v int64) *UsageLogPayloadUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogPayloadUpdate) SetNillableUsageLogID(v *int64) *UsageLogPayloadUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageLogPayloadUpdate) AddUsageLogID(v int64) *UsageLogPayloadUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *UsageLogPayloadUpdate) SetRequestBody(v string) *UsageLogPayloadUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *UsageLogPayloadUpdate) SetNillableRequestBody(v *string) *UsageLogPayloadUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *UsageLogPayloadUpdate) ClearRequestBody() *UsageLogPayloadUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *UsageLogPayloadUpdate) SetResponseBody(v string) *UsageLogPayloadUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *UsageLogPayloadUpdate) SetNillableResponseBody(v *string) *UsageLogPayloadUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *UsageLogPayloadUpdate) ClearResponseBody() *UsageLogPayloadUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetRequestTruncated sets the "request_truncated" field.
func (_u *UsageLogPayloadUpdate) SetRequestTruncated(v bool) *UsageLogPayloadUpdate {
	_u.mutation.SetRequestTruncated(v)
	return _u
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_u *UsageLogPayloadUpdate) SetNillableRequestTruncated(v *bool) *UsageLogPayloadUpdate {
	if v != nil {
		_u.SetRequestTruncated(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *UsageLogPayloadUpdate) SetResponseTruncated(v bool) *UsageLogPayloadUpdate {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *UsageLogPayloadUpdate) SetNillableResponseTruncated(v *bool) *UsageLogPayloadUpdate {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// Mutation returns the UsageLogPayloadMutation object of the builder.
func (_u *UsageLogPayloadUpdate) Mutation() *UsageLogPayloadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageLogPayloadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogPayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageLogPayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogPayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UsageLogPayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usagelogpayload.Table, usagelogpayload.Columns, sqlgraph.NewFieldSpec(usagelogpayload.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usagelogpayload.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usagelogpayload.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(usagelogpayload.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(usagelogpayload.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogpayload.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(usagelogpayload.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldRequestTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldResponseTruncated, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageLogPayloadUpdateOne is the builder for updating a single UsageLogPayload entity.
type UsageLogPayloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageLogPayloadMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogPayloadUpdateOne) SetUsageLogID(v int64) *UsageLogPayloadUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogPayloadUpdateOne) SetNillableUsageLogID(v *int64) *UsageLogPayloadUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageLogPayloadUpdateOne) AddUsageLogID(v int64) *UsageLogPayloadUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *UsageLogPayloadUpdateOne) SetRequestBody(v string) *UsageLogPayloadUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *UsageLogPayloadUpdateOne) SetNillableRequestBody(v *string) *UsageLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *UsageLogPayloadUpdateOne) ClearRequestBody() *UsageLogPayloadUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *UsageLogPayloadUpdateOne) SetResponseBody(v string) *UsageLogPayloadUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *UsageLogPayloadUpdateOne) SetNillableResponseBody(v *string) *UsageLogPayloadUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *UsageLogPayloadUpdateOne) ClearResponseBody() *UsageLogPayloadUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetRequestTruncated sets the "request_truncated" field.
func (_u *UsageLogPayloadUpdateOne) SetRequestTruncated(v bool) *UsageLogPayloadUpdateOne {
	_u.mutation.SetRequestTruncated(v)
	return _u
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_u *UsageLogPayloadUpdateOne) SetNillableRequestTruncated(v *bool) *UsageLogPayloadUpdateOne {
	if v != nil {
		_u.SetRequestTruncated(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *UsageLogPayloadUpdateOne) SetResponseTruncated(v bool) *UsageLogPayloadUpdateOne {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *UsageLogPayloadUpdateOne) SetNillableResponseTruncated(v *bool) *UsageLogPayloadUpdateOne {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// Mutation returns the UsageLogPayloadMutation object of the builder.
func (_u *UsageLogPayloadUpdateOne) Mutation() *UsageLogPayloadMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageLogPayloadUpdate builder.
func (_u *UsageLogPayloadUpdateOne) Where(ps ...predicate.UsageLogPayload) *UsageLogPayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageLogPayloadUpdateOne) Select(field string, fields ...string) *UsageLogPayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageLogPayload entity.
func (_u *UsageLogPayloadUpdateOne) Save(ctx context.Context) (*UsageLogPayload, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogPayloadUpdateOne) SaveX(ctx context.Context) *UsageLogPayload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageLogPayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogPayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UsageLogPayloadUpdateOne) sqlSave(ctx context.Context) (_node *UsageLogPayload, err error) {
	_spec := sqlgraph.NewUpdateSpec(usagelogpayload.Table, usagelogpayload.Columns, sqlgraph.NewFieldSpec(usagelogpayload.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageLogPayload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagelogpayload.FieldID)
		for _, f := range fields {
			if !usagelogpayload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagelogpayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usagelogpayload.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usagelogpayload.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(usagelogpayload.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(usagelogpayload.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogpayload.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(usagelogpayload.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldRequestTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogpayload.FieldResponseTruncated, field.TypeBool, value)
	}
	_node = &UsageLogPayload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
