// Code generated by ent, DO NOT EDIT.

package usagelogpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagelogpayload type in the database.
	Label = "usage_log_payload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldRequestTruncated holds the string denoting the request_truncated field in the database.
	FieldRequestTruncated = "request_truncated"
	// FieldResponseTruncated holds the string denoting the response_truncated field in the database.
	FieldResponseTruncated = "response_truncated"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the usagelogpayload in the database.
	Table = "usage_log_payloads"
)

// Columns holds all SQL columns for usagelogpayload fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldRequestBody,
	FieldResponseBody,
	FieldRequestTruncated,
	FieldResponseTruncated,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestTruncated holds the default value on creation for the "request_truncated" field.
	DefaultRequestTruncated bool
	// DefaultResponseTruncated holds the default value on creation for the "response_truncated" field.
	DefaultResponseTruncated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageLogPayload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByRequestBody orders the results by the request_body field.
func ByRequestBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBody, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByRequestTruncated orders the results by the request_truncated field.
func ByRequestTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestTruncated, opts...).ToFunc()
}

// ByResponseTruncated orders the results by the response_truncated field.
func ByResponseTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTruncated, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
