// Code generated by ent, DO NOT EDIT.

package usagelogpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldRequestBody, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldResponseBody, v))
}

// RequestTruncated applies equality check predicate on the "request_truncated" field. It's identical to RequestTruncatedEQ.
func RequestTruncated(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldRequestTruncated, v))
}

// ResponseTruncated applies equality check predicate on the "response_truncated" field. It's identical to ResponseTruncatedEQ.
func ResponseTruncated(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldResponseTruncated, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLTE(FieldUsageLogID, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldContainsFold(FieldRequestBody, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldContainsFold(FieldResponseBody, v))
}

// RequestTruncatedEQ applies the EQ predicate on the "request_truncated" field.
func RequestTruncatedEQ(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldRequestTruncated, v))
}

// RequestTruncatedNEQ applies the NEQ predicate on the "request_truncated" field.
func RequestTruncatedNEQ(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldRequestTruncated, v))
}

// ResponseTruncatedEQ applies the EQ predicate on the "response_truncated" field.
func ResponseTruncatedEQ(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldResponseTruncated, v))
}

// ResponseTruncatedNEQ applies the NEQ predicate on the "response_truncated" field.
func ResponseTruncatedNEQ(v bool) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldResponseTruncated, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLogPayload) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLogPayload) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLogPayload) predicate.UsageLogPayload {
	return predicate.UsageLogPayload(sql.NotPredicates(p))
}
